### ISSUE TITLE
Support Java 11 Migrations

### ISSUE THREAD

**Issue by bentatham** [flyway/flyway-docker#10]
For Java Migrations, it would be nice to be able to use Java 11 (instead of forcing Java 8).

Assuming flyway itself can run in Java 11, this requires a simple update to the Dockerfile to   `FROM openjdk:11-jre` instead of openjdk:8-jre (or pick your favorite version -- perhaps slim or something else).

**Comment by axelfontaine** [comment]
This will be updated as part of Flyway 6.0.0 where the CLI now also ships with Java 11

**Comment by axelfontaine** [comment]
This has now been implemented in the 6.0.0-beta2 image
