### ISSUE TITLE
No flyway user in alpine docker images since tag v9.2.2

### ISSUE THREAD

**Issue by karlroberts** [flyway/flyway-docker#106]
Just checking is this a bug or regression? If so I'll push  a PR

It gave me issues on a custom image extended from yours. I could work around by adding this to my custom image

```
USER root
RUN addgroup flyway && adduser -S -h /flyway -D -G flyway flyway

WORKDIR /flyway
USER flyway
```

Cheers

Karl

**Comment by Barry-RG** [comment]
This was an intended change. 
Your work around should be valid for your intent.
