### ISSUE TITLE
Flyway 9.4.0 missing from hub.docker.com, Releases, this repo

### ISSUE THREAD

**Issue by kebeda** [flyway/flyway-docker#109]
Flyway 9.4.0 has been out at least a week, with no signs of it appearing on hub.docker.com.
Although I can find the release on the flyway/flyway repo, there is no sign of it in this repo, indeed the last release I see here is for 7.5.1, over a year ago. Did this repo move?

**Comment by yoomlam** [comment]
Same. Using Docker instructions from https://flywaydb.org/documentation/usage/commandline, I get an error:
```
> docker pull flyway/flyway:9.4.0
Error response from daemon: manifest for flyway/flyway:9.4.0 not found: manifest unknown: manifest unknown
```
because it's not there: https://hub.docker.com/r/flyway/flyway/tags

**Comment by holophil** [comment]
Is there any progress planned on this one? I think there is nothing that the community can assist here.

Still the images for the recently released version 9.4 are missing at https://hub.docker.com/r/flyway/flyway/tags

**Comment by DoodleBobBuffPants** [comment]
Sorry about this, 9.4.0 docker images should now be available

**Comment by holophil** [comment]
Yes, they are. Thanks a lot!

Following up on this: 9.5 just got released. Will these be pushed soon as well? Can we get a release notification for this repository as well?
