### ISSUE TITLE
Flyway Docker hub deployment 

### ISSUE THREAD

**Issue by Barry-RG** [flyway/flyway-docker#120]
Due to an on-going refactoring process, we are currently suspending deployment of Flyway to Docker hub until this process has been completed. 
Sorry for the inconvenience. 
This will affect releases from 9.16.2.

**Comment by kmgreen2** [comment]
@Barry-RG Do you have an eta for when the deployment will continue?  There are a few CVEs affecting 9.16.1 that are fixed in 9.16.2.  Thanks!

**Comment by Barry-RG** [comment]
@kmgreen2 We are looking to return to normal release flows (including Docker etc) next week

**Comment by Barry-RG** [comment]
We have now resolved this issue and returning to regular release processes
