### ISSUE TITLE
Missmatch between Versioning on README.MD and actual Dockerfile

### ISSUE THREAD

**Issue by OberstK** [flyway/flyway-docker#13]
Currently the links for latest in the README.MD are actually pointing to the Dockerfile in master containing "6.0.0-beta2" as the version ENV and not to the 5.2.5 last stable release as indicated by the link Text in the README.MD

Not sure what the expected outcome here is? Latest should not point to a beta release imo. Instead it should be a tag of its own.

The same behaviour is true for the alpine tags

**Comment by alextercete** [comment]
Thanks for reporting this! 🙏 

I'll close this as it should no longer be a problem now that version 6 has been released.
