### ISSUE TITLE
Latest image can't connect to jdbc

### ISSUE THREAD

**Issue by paulSambolin** [flyway/flyway-docker#135]
Hey we started seeing connection issues around 12PM EST.  Pinning to older version resolved connection issues
```
# flyway/flyway:latest-alpine
ERROR: Unable to connect to jdbc:mysql://<db host>:3306/<dbname>?enabledTLSProtocols=TLSv1.2&createDatabaseIfNotExist=true

# flyway/flyway:10.6-alpine
Success!
```

**Comment by tjs145** [comment]
This is a compatibility issue in the latest version of the MariaDB driver, which the Flyway CLI uses for both MariaDB and MySQL connections (the issue being that it no longer supports MySQL URLs by default). While we investigate a proper solution, here are some possible workarounds:

 - Add `&permitMysqlScheme=true` onto the end of your URL.
 - Download the [MySQL driver](https://mvnrepository.com/artifact/com.mysql/mysql-connector-j) and add it to the `drivers` folder in the docker container. (I'm not sure if there's an easy way of doing this in Docker. Perhaps by mapping a volume containing the MySQL driver onto the `drivers` folder.)

**Comment by paulSambolin** [comment]
Confirmed `&permitMysqlScheme=true` works with the latest version.  Thank you @tjs145 I will close the issue.  Please re-open if needed

**Comment by mrairzuk** [comment]
Got same error with PostgreSQL DB. Was working fine with previous version.

Flyway OSS Edition 10.7.1 by Redgate
See release notes here: https://rd.gt/416ObMi
ERROR: Unable to connect to the database. Configure the url, user and password!

**Comment by mrairzuk** [comment]
> Got same error with PostgreSQL DB. Was working fine with previous version.
> 
> Flyway OSS Edition 10.7.1 by Redgate See release notes here: https://rd.gt/416ObMi ERROR: Unable to connect to the database. Configure the url, user and password!

Downgrading to 10.6 resolves this error. I am using Docker image and configure connection using environment variables
