### ISSUE TITLE
Can flyway-docker be used as a server?

### ISSUE THREAD

**Issue by ajhool** [flyway/flyway-docker#15]
I notice that the docker compose example automatically executes migrate on spin up. Our use case is to spin up a flyway container and then execute commands, can flyway-docker be used as a server in that way?

**Comment by alextercete** [comment]
@ajhool I'm not sure I understand your question, can you give an example of how you'd like to use it (what kinds of commands you want to execute and why)?

**Comment by alextercete** [comment]
Closing due to lack of response.
