### ISSUE TITLE
[Enhancement] reduce Docker image size

### ISSUE THREAD

**Issue by davidpelfree** [flyway/flyway-docker#23]
Looking at [Docker hub](https://hub.docker.com/r/flyway/flyway/tags), I see that flyway Docker image size is about 130 MB.

Alpine based image size is around 107 MB.

Using [dive](https://github.com/wagoodman/dive) I see that there are 2 big things in the image:

1. "drivers" directory inside downloaded "flyway-commandline-6.3.2.tar.gz" file (59 MB)
2. openjdk-8-jre (79 MB)

In order to reduce Docker image size we can:
1. Create many smaller DB-specific Docker images, so only required drivers will be packed.
2. Use tools like [Quarkus](https://quarkus.io/guides/building-native-image) to create small *native* Java app, which doesn't require the full Java JRE

What do you think?

**Comment by guillaumBrisard** [comment]
It will be great to reduce image size.
I use it in Concourse-CI and with an InitContainer in K8s and it takes too much time.
Maybe one image for each DB, it's too much. Perhaps just one more image with no driver.

**Comment by DoodleBobBuffPants** [comment]
Perhaps we will revisit this one day, but closing for now
