### ISSUE TITLE
feat(base-images): provide a distroless images

### ISSUE THREAD

**Issue by davinkevin** [flyway/flyway-docker#26]
Hi, 

I would like to propose the alternative to alpine images based on [distroless](https://github.com/GoogleContainerTools/distroless). This solution has the advantage to provide no shell and being updated by Google and relying on an official OpenJDK (tested against the TCK). 

This is for security and reliability the best solution we choose to deploy our application in potentially insecure system. 

For information, I've made an image for flyway for my favorite pet project [here](https://gitlab.com/davinkevin/Podcast-Server/-/blob/master/database/Dockerfile). I choose to strip down jars not required for my use case by the way.

**Comment by gajus** [comment]
Shell is needed for using flyway image in CI/CD environments, such as GitLab.

**Comment by davinkevin** [comment]
Yeah but a :debug version can be provided based on the :debug version of the distroless image

**Comment by DoodleBobBuffPants** [comment]
Perhaps we will revisit this one day, but closing for now
