### ISSUE TITLE
Revert flyway back to JDK11

### ISSUE THREAD

**Issue by otrosien** [flyway/flyway-docker#38]
I have seen that this PR https://github.com/flyway/flyway-docker/pull/30 bumped the base image for flyway from JDK11 to JDK12. Please consider reverting this back to the current LTS, which is JDK11.

**Comment by DoodleBobBuffPants** [comment]
Is there anything about the current images that prevents you from using them?

**Comment by ghost** [comment]
I have the same request. JDK11 is LTS, while JDK12 is not. Unless there are specific features of JDK12 that are used in Flyway, I would very much appreciate if Docker images would be based on LTS versions of JDK.

**Comment by DoodleBobBuffPants** [comment]
This makes sense, however as there isn't an official alpine image for JDK 11 our alpine image will remain at JDK 12 for now

**Comment by DoodleBobBuffPants** [comment]
See https://github.com/flyway/flyway-docker/pull/39
