### ISSUE TITLE
Running flyway:5.2.1-alpine errors with syntax error

### ISSUE THREAD

**Issue by FBryant87** [flyway/flyway-docker#4]
When running `docker run boxfuse/flyway:5.2.1-alpine`, we get the following error:

> /usr/local/bin/flyway: line 52: syntax error: unexpected "("

This has only started happening this afternoon, so it looks like it could be to do with commit https://github.com/flyway/flyway-docker/commit/c3926fb96bf3cf279298eb6f48f7769e5a3034b2.

**Comment by bensquire** [comment]
I can confirm this...

**Comment by axelfontaine** [comment]
Ahh very interesting! It looks we just ran into an incompatibility between Alpine's busybox and bash. And seems to have to do with arrays: https://github.com/flyway/flyway/blob/master/flyway-commandline/src/main/assembly/flyway#L52

Would you like to submit a pull request to https://github.com/flyway/flyway with a fix?

**Comment by axelfontaine** [comment]
Cleaned up the image to add the real bash instead.
