### ISSUE TITLE
Failure when running in K8s

### ISSUE THREAD

**Issue by twerthi** [flyway/flyway-docker#40]
I've been attempting to get this container to run in Kubernetes without success.  I've created an image where the only change is copying some .SQL files into the flyway/sql folder

```
# Get base image
FROM flyway/flyway

# Copy script files to container
COPY /sql ./sql/

# List files to show they are present
RUN ls ./sql/
```

When running in docker-compose, this works perfectly, the database container is updated from the scripts included.  When running in Kubernetes, the container fails with a StartError status.  Listing out the events, I see the following

```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "-url=jdbc:mysql://mysql-cluster-ip:3306/petclinic?useUnicode=true&useSsl=false -user=root -password=XXXX migrate": stat -url=jdbc:mysql://mysql-cluster-ip:3306/petclinic?useUnicode=true&useSsl=false -user=root -password=XXXXX migrate: no such file or directory: unknown
```

Have I done something incorrectly?

**Comment by DoodleBobBuffPants** [comment]
The command it is trying to exec looks wrong, since it should be prepended with `flyway`. In Kubernetes you may need to set the `command` to be the same as our Dockerfile's `ENTRYPOINT` since it looks like it is only trying to exec the args without any command
