### ISSUE TITLE
Alpine Flyway image is bigger than non-Alpine image. Base Alpine image on adoptopenjdk/openjdk11:alpine-jre.

### ISSUE THREAD

**Issue by haroldlbrown** [flyway/flyway-docker#45]
I have just pulled `flyway/flyway:latest` and `flyway/flyway:latest-alpine`.

I would have thought that `flyway/flyway:latest-alpine` is smaller than `flyway/flyway:latest`, since it uses Alpine Linux. 

However, this is not the case.

```
flyway/flyway                                    latest                     ee3f89e9f195   20 hours ago     309MB
flyway/flyway                                    latest-alpine              20815525351c   20 hours ago     389MB
```

`latest-alpine` is 80 MB **bigger** than `latest`. I guess the reason is for `latest-alpine` being based on `openjdk:16-alpine`, which includes a JDK and not a JRE.

Please base `latest-alpine` on [`adoptopenjdk/openjdk11:alpine-jre`](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/11/jre/alpine/Dockerfile.hotspot.releases.full) to reduce image size.

**Comment by DoodleBobBuffPants** [comment]
We updated the base image due to a vulnerability, and will stick with openjdk as opposed to adoptopenjdk for now, and will consider this for the future

You should be able to use your own dockerfile based on adoptopenjdk for now however
