### ISSUE TITLE
Latest tag uses version 7.5.4 instead of the latest (currently 7.7.3)

### ISSUE THREAD

**Issue by zikato** [flyway/flyway-docker#48]
docker run flyway/flyway:latest info

Flyway Community Edition 7.5.4 by Redgate
ERROR: Unable to connect to the database. Configure the url, user and password!

**Comment by DoodleBobBuffPants** [comment]
You likely have an existing image with the latest tag which is an older version of the Flyway image

Deleting your existing local images and pulling those images again should resolve this
