### ISSUE TITLE
useradd: invalid user name 'AzDevOps_azpcontainer' in flyway-azure containers.

### ISSUE THREAD

**Issue by eking-go** [flyway/flyway-docker#54]
Hello.

```
Digest: sha256:bed2f68845aa0888bd3d6742eb7fdf246877be765e63bb05f7fefb7eaed1aba7
Status: Downloaded newer image for flyway/flyway-azure:7.2.1-alpine
/flyway # useradd -m -u 1001 AzDevOps_azpcontainer
useradd: invalid user name 'AzDevOps_azpcontainer'
```

Because of it container does not work with azure devops.

Maybe this is reason https://github.com/atmoz/sftp/issues/109

**Comment by eking-go** [comment]
With the latest version of the image - the same problem.

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know, however, as you have linked, this is an issue with alpine and we won't be able to make a change to fix this, but we'll consider solutions and come back to this case if there is more traction

**Comment by eking-go** [comment]
May be possible to use another source image, without this problem? For example - Debian.
