### ISSUE TITLE
Migrate base image to Eclipse Temurin

### ISSUE THREAD

**Issue by emiel** [flyway/flyway-docker#56]
The [AdoptOpenJDK docker hub docs](https://hub.docker.com/_/adoptopenjdk) state that the AdoptOpenJDK images have been deprecated and to switch over to [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin/).

**Comment by visit1985** [comment]
Alpine based images are available from Temurin now. – https://github.com/adoptium/containers/issues/72#issuecomment-952748724
