### ISSUE TITLE
support apple silicon

### ISSUE THREAD

**Issue by chauchakching** [flyway/flyway-docker#60]
When the `amd64` platform image is used for running flyway, no log at all from the docker container.

So I tried to build the flyway image locally. After changing the `Dockerfile` base image to use latest version of `eclipse-temurin`, and build it with platform flag `linux/arm64`, the image works.

**Comment by DoodleBobBuffPants** [comment]
Closing as duplicate of https://github.com/flyway/flyway-docker/issues/37

**Comment by okanji** [comment]
@chauchakching, could you please share your Dockerfile with these changes?
