### ISSUE TITLE
Version 8.5.0 is older than flyway:master

### ISSUE THREAD

**Issue by ticteam** [flyway/flyway-docker#66]
Hello, 
the Version [8.5.0](https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.0/) 
which is used to build the docker image is older than [flyway:master](https://github.com/flyway/flyway) 
with the following [PR](https://github.com/flyway/flyway/pull/3397/files) was an update of the jackson-databind 

but when unpacking the 8.5.0  
there is still the jackson-databind-2.10.5.1.jar in the [8.5.0](https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.0/) 

could you pls fix that ?
greetings

**Comment by DoodleBobBuffPants** [comment]
The docker image will be updated during our next release

**Comment by ticteam** [comment]
could you update the Version https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.5.x 
beforehand ?
