### ISSUE TITLE
Alpine image for arm64

### ISSUE THREAD

**Issue by jlamande** [flyway/flyway-docker#73]
_This is a feature request._

Our Kubernetes platform is running on arm64 processors, and using the alpine flavor of the flyway image would be appreciated since it is lighter.

Any reason to not make use of `buildx` for Alpine in the Makefile ?

_and thanks for the great flyway product_

**Comment by Barry-RG** [comment]
Unfortunately, there does not seem to be a reliable officially maintained base image for a Java 11 JRE on Alpine for arm64. 
As a result, using `buildx` would not work for this architecture. We are very aware of the desire for more architecture for the alpine image but until the correct base images are available, we can unfortunately not support them. Please keep an eye on our this repository or our Dockerhub page for any more developments. 
Until then, the base Flyway image supports arm64 but, as you may have observed, it is not as lightweight.

**Comment by Barry-RG** [comment]
Waiting on https://github.com/adoptium/containers/issues/158
