### ISSUE TITLE
Mismatch between latest-alpine and 8.5.9-alpine

### ISSUE THREAD

**Issue by hemberger** [flyway/flyway-docker#74]
The `8.5.9-alpine` image should have the same digest as `latest-alpine`, but they are currently different:

![image](https://user-images.githubusercontent.com/846186/164643844-a0ce07ff-1825-4bbb-b20b-3d57daa2af3c.png)

It is also a bit odd that `latest-alpine` is the only image pushed by the `flyway` user (all others are pushed by `redgateci`).

I'm not exactly sure what's different between these two images, but something is seriously wrong with `latest-alpine`. Any migration I run reports that all my checksums have a mismatch. If I switch to `8.5.9-alpine`, then without changing any files all migrations are successfully validated. Both images are reporting "Flyway Community Edition 8.5.9 by Redgate".

If more details are needed, please let me know. Thanks for your time!

**Comment by Barry-RG** [comment]
Thank you for raising this. We have updated our pipeline to fix this inconsistency.
