### ISSUE TITLE
Alpine image checksums broken since 8.5.10

### ISSUE THREAD

**Issue by hemberger** [flyway/flyway-docker#84]
Using image `8.5.10-alpine` or `8.5.11-alpine`, all of my checksum validations are failing. If I use `8.5.9-alpine`, or any of the non-alpine variants, then all my checksum validations pass. These are the same checksum errors that I was seeing with `8.5.9-alpine` (which is fine now) in #74. I don't see any such discrepancy on DockerHub this time, however.

I'm at a loss for how to fix this on my end, short of purging my entire Docker installation. If there's any information I can provide to help resolve this issue, please let me know. If you don't think this is a Flyway problem, you can close this issue with my apologies for bothering you!

**Comment by DoodleBobBuffPants** [comment]
This doesn't seem to be a Flyway issue, the checksums look correct on our end and we haven't been able to reproduce this
It may be a result of image caching so purging that might help
If you're able to reproduce this we can investigate further, but closing for now
