### ISSUE TITLE
Add rx flags in order to make it easy to run as random UID

### ISSUE THREAD

**Issue by davidkarlsen** [flyway/flyway-docker#85]
It would be nice if you can add `chmod -R a+rx /flyway` (or at least `chmod a+rx /flyway/flyway`) in order to make the image runnable by any UID. Typically one runs under a restricted UID on various k8s platforms, and in particular OpenShift assigns a high-range UID per namespace, as described here: https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids

**Comment by davidkarlsen** [comment]
@DoodleBobBuffPants PTAL?

**Comment by Barry-RG** [comment]
@davidkarlsen is this for use of Flyway Community or of Flyway Teams?

If this is for Teams, does `docker pull redgate/flyway` cause you the same issue?

**Comment by davidkarlsen** [comment]
> @davidkarlsen is this for use of Flyway Community or of Flyway Teams?
> 
> If this is for Teams, does `docker pull redgate/flyway` cause you the same issue?


@Barry-RG 
teams - but both images have the same issue which is a deal-breaker for openshift users:

```
docker run --rm -u 9999 redgate/flyway
exec /flyway/flyway: permission denied
```
