### ISSUE TITLE
Add Image for ARM processors

### ISSUE THREAD

**Issue by bridger217** [flyway/flyway-docker#95]
Hi,

I'm on the Apple M1 Pro and when try to run flyway migrate from the `flyway/flyway:7` container, it hangs indefinitely.

I believe it's because the image is only built for amd64. Can you add an arm64 version?

**Comment by DoodleBobBuffPants** [comment]
Closing as duplicate of https://github.com/flyway/flyway-docker/issues/37

arm images should work but Flyway V8 (more specifically I believe 8.5.0)
